import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import baseline from '../samples/prepared-workspace.json' with {type:'json'};
import {progressTool,PROGRESS_TOOLS} from '../server/progress-mcp.mjs';
import {cloudDatabase} from '../server/cloud-db.mjs';
import {sqliteD1} from './cloud-fixtures.mjs';
function setup(t,w=baseline){const DB=sqliteD1();t.after(()=>DB.close());const db=cloudDatabase(DB),call=async(name,args={},user='owner')=>{const value=await progressTool(name,args,user,{DB}),s=PROGRESS_TOOLS.find(t=>t.name===name).outputSchema;const v=spawnSync('python',['-c','import json,sys,jsonschema; s,v=json.load(sys.stdin); jsonschema.Draft202012Validator.check_schema(s);jsonschema.validate(v,s)'],{input:JSON.stringify([s,value]),encoding:'utf8'});assert.equal(v.status,0,v.stderr);return value;};return {db,call,seed:()=>db.save('owner',{baseVersion:0,operationId:'progress-test-seed',workspace:structuredClone(w)})};}
const args=p=>({baseVersion:p.baseVersion,previewDigest:p.previewDigest,operationId:p.operationId});
test('fixed progress updates preserve estimates, original evidence, history and human acceptance',async t=>{
 const w=structuredClone(baseline);w.projects[0].data.tasks[1].estimatePoints=.5;const h=setup(t,w);await h.seed();const p=await h.call('preview_progress_update');assert.equal(p.changes.length,4);assert.equal((await h.db.load('owner')).version,1);const r=await h.call('apply_progress_update',args(p));assert.equal(r.count,4);const saved=await h.db.load('owner');
 for(const project of w.projects){const actual=saved.workspace.projects.find(x=>x.id===project.id);assert.deepEqual(actual.data.history.slice(-project.data.history.length),project.data.history);for(const task of project.data.tasks){const after=actual.data.tasks.find(x=>x.id===task.id),change=p.changes.find(c=>c.projectId===project.id&&c.taskId===task.id);if(!change)assert.deepEqual(after,task);else{assert.equal(after.estimatePoints,task.estimatePoints);assert.deepEqual(after.criteria.map(c=>c.text),task.criteria.map(c=>c.text));assert.ok(after.evidence.startsWith(task.evidence));assert.equal(after.status,change.after.status);}}}
 const before=structuredClone(saved);assert.equal((await h.call('apply_progress_update',args(p))).replayed,true);assert.deepEqual(await h.db.load('owner'),before);assert.equal((await h.call('preview_progress_update')).changes.length,0);
});
test('edited prerequisites and dependent tasks are skipped without erasing owner changes',async t=>{const w=structuredClone(baseline);w.projects[0].data.tasks[1].evidence+=' user edit';const h=setup(t,w);await h.seed();const p=await h.call('preview_progress_update');assert.equal(p.changes.length,2);assert.equal(p.skipped.length,2);await h.call('apply_progress_update',args(p));assert.deepEqual((await h.db.load('owner')).workspace.projects[0],w.projects[0]);});
test('version conflicts, another owner and unknown write fields reject without writes',async t=>{const h=setup(t);await h.seed();const p=await h.call('preview_progress_update');await assert.rejects(h.call('apply_progress_update',{...args(p),userId:'owner'}));await assert.rejects(h.call('apply_progress_update',args(p),'other'));const old=await h.db.load('owner');await h.db.save('owner',{baseVersion:1,operationId:'newer-owner-write',workspace:old.workspace});await assert.rejects(h.call('apply_progress_update',args(p)),/更新/);assert.equal((await h.db.load('owner')).version,2);});
test('empty workspaces have a no-op preview and do not create tasks',async t=>{const h=setup(t);const p=await h.call('preview_progress_update');assert.equal(p.changes.length,0);assert.equal((await h.call('apply_progress_update',args(p))).applied,false);assert.equal((await h.db.load('owner')).version,0);});
